sudo: required
dist: trusty
language: cpp
os:
  - osx
matrix:
  include:
    - os: linux
      env: COMPILER=g++-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER=clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
script: >
    cmake -DCXXOPTS_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER=$COMPILER .
    && make && make ARGS=--output-on-failure test
